export const RECEIVE_ADDRESS = 'receive_address' //获取位置信息
export const RECEIVE_CATEGORYS = 'receive_categorys' //获取食品分类列表
export const RECEIVE_SHOPS = 'receive_shops' //获取商家列表
export const RECEIVE_USER_INFO = 'receive_user_info' // 接收用户信息
export const RESET_USER_INFO = 'reset_user_info' // 退出登录
export const RECEIVE_GOODS = 'receive_goods' // 获取商家商品信息
export const RECEIVE_RATINGS = 'receive_ratings' // 获取商家评价信息
export const RECEIVE_INFO = 'receive_info' // 获取商家信息
export const INCREMENT_FOOD_COUNT = 'increment_food_count' //添加food count
export const DECREMENT_FOOD_COUNT = 'decrement_food_count' //减少food count
export const CLEAR_CART = 'clear_cart' // 清空购物车
